name: First Workflow
on: workflow_dispatch
jobs: 
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: FirstStep
        run: |
          echo "helloWorld"
          echo "bye"

          
